### ISSUE TITLE
Link error in readme

### ISSUE THREAD

**Issue by jothoma1** [cvtienhoven/graylog-plugin-sensu#1]
Hello
thanks for this great plugin :)
Just a small fix in your readme, the link for downloading the jar is broken. It should be : https://github.com/cvtienhoven/graylog-plugin-sensu/releases

Thanks !

**Comment by cvtienhoven** [comment]
@jothoma1 thanks for using the plugin and your comment, I fixed it (will be released when other issues/features will be incorporated).
