### ISSUE TITLE
Cannot send test alerts to sensu

### ISSUE THREAD

**Issue by jothoma1** [cvtienhoven/graylog-plugin-sensu#2]
Hi, i'm trying to send alerts to sensu but i'm having some problems;
When i try the notifications, it always failed with : "**Sending test alert notification failed with message: cannot POST https://mygraylogcluster/api/alerts/callbacks/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/test**"

I'm using Graylog 2.2.3.
Do you have an idea ? My Graylog sensu config seems to be ok (sensu works)

Thanks in advance
Johan

**Comment by cvtienhoven** [comment]
Well the alerting mechanism of Graylog has been adapted a bit from 2.1 to 2.2, so I can imagine that Alarm Callback plugins should now implement a test method, which hasn't been done yet for the Sensu Alarm Callback plugin. It might however work perfectly, we're using the plugin ourselves with version 2.2.2. of Graylog. But I'll look into this, thanks for submitting this issue.

**Comment by jothoma1** [comment]
Thanks for your explanation for this test alert behavior. I will open another issue as it's not the same problem (ssl problem i think)

**Comment by cvtienhoven** [comment]
Closed this issues as it's said to work in #3

**Comment by jothoma1** [comment]
:+1:
